baseURL = "https://apuntesderust.netlify.app/"
title = "Apuntes de Rust"
languageCode = "es-es"
theme = "hyde"
enableGitInfo = "true"

[params]
  description = "Una serie de anotaciones útiles en mi largo y tortuoso camino de aprendizaje de Rust."